### ISSUE TITLE
Question about the paper and implementation (IC, and CC evaluation)

### ISSUE THREAD

**Issue by jihoontack** [boschresearch/what-matters-for-meta-learning#1]
Hi, thank you for the awesome work, also the implementations are awesome!

While reading your paper, I have seen you evaluated the ShapeNet dataset for both intra-category (IC) and cross-category (CC) levels.

However, it was hard for me to find the options in the implementation.
How can I evaluate IC and CC on this implementation?

Thank you again for the awesome work!

Best,
Jihoon

**Comment by gaobaoding** [comment]
Hi @jihoontack,

Thanks for your interest in our work. Evaluations on both IC and CC are executed automatically using
```
python evaluation.py --config cfg/evaluation/${config file}
```
which will then run the [code](https://github.com/boschresearch/what-matters-for-meta-learning/blob/78d94aea9ce585494d3e4b1fb864139888d94741/evaluator/model_evaluator.py#L95-L122). 
Also, you can use a for-loop to evaluate the performance with different number of contexts as shown in the paper. 

Best,
Ning

**Comment by jihoontack** [comment]
Thank you very much for the answer!

Really enjoyed reading your paper
